language: php

sudo: required

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@evoweb.de

before_script:
  - phpenv config-rm xdebug.ini

install:
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - export COMPOSER_ROOT_VERSION=5.0.3
  - |
    composer require \
      typo3/minimal="$TYPO3_VERSION" \
      $PREFER_LOWEST
  - git checkout composer.json

script:
  - echo "no phpunit testing for now"

jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="^9.1.0"
    - env: TYPO3_VERSION="dev-master as 9.2.0"


  include:
    - &lint
      stage: test
      php: 7.2
      env: PHP Lint
      before_install: skip
      install: skip
      before_script: skip
      script:
        - errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
    - <<: *lint
      php: 7.1
    - <<: *lint
      php: 7.0

    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^9.1.0"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master as 9.2.0"

    - stage: publish in ter
      if: tag IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";

            # Install requirements
            composer require --dev helhum/ter-client dev-master

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Set version number from tag
            sed -i "s/version' => '.*'/version' => '${TRAVIS_TAG}'/" ext_emconf.php

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            .Build/bin/ter-client upload ew_llxml2xliff . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
